[window]
opacity = 0.95
startup_mode = 'Maximized'

[font]
normal = {family = 'TerminessNerdFont', style = 'Light'}
bold = {family = 'TerminessNerdFont', style = 'Light'}
italic = {family = 'TerminessNerdFont', style = 'Light'}
size = 12.0
offset = {x=1, y=1}
