[window]
opacity = 0.95

[font]
normal = {family = 'PixelOperatorMono', style = 'Light'}
bold = {family = 'PixelOperatorMono', style = 'Light'}
italic = {family = 'PixelOperatorMono', style = 'Light'}
size = 16
offset = {x=0, y=0}
